root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/api ./cmd/api"
bin = "./tmp/api"
include_ext = ["go", "tpl", "tmpl", "html", "env"]
exclude_dir = ["tmp", "vendor", ".git"]
delay = 200
stop_on_error = true
